# Generated by Django 3.1.7 on 2021-03-04 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroHoraExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'RegistroHoraExtra',
                'verbose_name_plural': 'RegistrosHoraExtra',
            },
        ),
    ]
